spring.application.name=auction
# MySQL DB Connection
spring.datasource.url=jdbc:mysql://localhost:3307/auction_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=auction_user
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate/JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis Connection
spring.data.redis.host=localhost
spring.data.redis.port=6379